name: mpa
channels: !!python/tuple
- defaults
dependencies:
- conda-forge::audioread=2.1.4=py35_2
- conda-forge::cycler=0.10.0=py35_0
- conda-forge::cython=0.25.2=py35_0
- conda-forge::decorator=4.0.10=py35_0
- conda-forge::ffmpeg=2.8.6=3
- conda-forge::freetype=2.6.3=1
- conda-forge::joblib=0.10.3=py35_0
- conda-forge::libpng=1.6.28=0
- conda-forge::librosa=0.4.3=py35_0
- conda-forge::matplotlib=2.0.0=np111py35_0
- conda-forge::pyparsing=2.1.10=py35_0
- conda-forge::python-dateutil=2.6.0=py35_0
- conda-forge::pytz=2016.10=py35_0
- conda-forge::resampy=0.1.4=np111py35_0
- conda-forge::six=1.10.0=py35_1
- conda-forge::x264=20131217=1
- libgcc=4.8.5=1
- mkl=2017.0.1=0
- numpy=1.11.3=py35_0
- openssl=1.0.2j=0
- pip=9.0.1=py35_1
- python=3.5.2=0
- readline=6.2=2
- scikit-learn=0.18.1=np111py35_1
- scipy=0.18.1=np111py35_1
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
prefix: /Users/deepsheaper/miniconda3/envs/mpa

